[package]
name = "gazeguard"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "gazeguard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[package.metadata]

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22"
tracing-subscriber = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.25"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_SystemInformation",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
tauri-plugin-tracing = { git = "https://github.com/fltsci/tauri-plugin-tracing", features = ["profiling"] }
tauri-plugin-autostart = "2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tauri-plugin-shell = "2.3.4"
fastrand = "2"
tracing = "0.1"
