version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      cargo-dependencies:
        patterns:
          - "*"
      cargo-security:
        applies-to: security-updates
        patterns:
          - "*"
